# Arabic Poetry Mood Labeling

In [1]:
import pandas as pd
import regex as re
import os
from pathlib import Path

In [2]:
!git clone https://github.com/akbargherbal/arabic-poetry-mood-labeling.git

Cloning into 'arabic-poetry-mood-labeling'...
remote: Enumerating objects: 134, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 134 (delta 3), reused 9 (delta 2), pack-reused 123 (from 1)
Receiving objects: 100% (134/134), 128.29 MiB | 13.72 MiB/s, done.
Resolving deltas: 100% (38/38), done.
Updating files: 100% (59/59), done.

In [3]:
%cd arabic-poetry-mood-labeling

/content/arabic-poetry-mood-labeling

In [4]:

df = pd.read_pickle('./TOP_100_ARABIC_POETS_OF_ALL_TIME_STAGE_02A.pkl')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21868 entries, 0 to 21867
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   POET_NAME   21868 non-null  object
 1   poem_no     21868 non-null  object
 2   batch_no    21868 non-null  int64
 3   POET_RANK   21868 non-null  int64
 4   meter       21868 non-null  object
 5   DATA        21868 non-null  object
 6   BATCH_SIZE  21868 non-null  int64
dtypes: int64(3), object(4)
memory usage: 1.2+ MB

In [5]:
df.sample()

,POET_NAME,poem_no,batch_no,POET_RANK,meter,DATA,BATCH_SIZE
12800,كثير عزه,22002,2,52,taweel,"[{'verse_id': '22002_024', 'sadr': 'بما قد أرى...",6

In [ ]:
df.describe()

           batch_no     POET_RANK    BATCH_SIZE
count  23979.000000  23979.000000  23979.000000
mean       1.970349     44.768714     10.245006
std        3.626990     29.061066      3.319789
min        0.000000      1.000000      1.000000
25%        0.000000     17.000000     11.000000
50%        1.000000     41.000000     12.000000
75%        2.000000     70.000000     12.000000
max       63.000000    100.000000     12.000000

In [1]:
from getpass import getpass

# token = getpass("GitHub Personal Access Token: ")

In [2]:
# import subprocess

# USERNAME = "akbargherbal"
# REPO = "arabic-poetry-mood-labeling"

# subprocess.run([
#     "git", "config", "--global", "user.name", "Your Name"
# ], check=True)

# subprocess.run([
#     "git", "config", "--global", "user.email", "your@email.com"
# ], check=True)

# subprocess.run([
#     "git", "remote", "set-url", "origin",
#     f"https://{USERNAME}:{token}@github.com/{USERNAME}/{REPO}.git"
# ], check=True)

In [9]:
!ls

arabic_poetry_moode_labeling.ipynb
checkpoints
checkpoint_utils.py
label_moods.py
merge_small_batches.py
notebook.ipynb
__pycache__
README.md
TOP_100_ARABIC_POETS_OF_ALL_TIME_STAGE_02A.pkl
TOP_100_ARABIC_POETS_OF_ALL_TIME_STAGE_02_mood_labeled.pkl
TOP_100_ARABIC_POETS_OF_ALL_TIME_STAGE_02.pkl

In [10]:
# !rm -rf checkpoints/

In [11]:
# Example 1: Run with checkpointing and auto-git-push every 4 chunks (each chunk is 500 rows)
!python label_moods.py TOP_100_ARABIC_POETS_OF_ALL_TIME_STAGE_02A.pkl --device cuda --batch-size 128 --chunk-size 500 --push-every 4

# Example 2: Run with local checkpoints only (disable automatic git pushing)
# !python label_moods.py TOP_100_ARABIC_POETS_OF_ALL_TIME_STAGE_02.pkl --device cuda --batch-size 128 --chunk-size 500 --no-git-push

[1/5] Loading dataframe from TOP_100_ARABIC_POETS_OF_ALL_TIME_STAGE_02A.pkl ...
      21868 rows loaded.
[2/5] Building batch texts ...
[3/5] Loading embedding model (BAAI/bge-m3) ...
      Using device: cuda
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100% 391/391 [00:00<00:00, 17470.50it/s]
[4/5] Encoding batch texts (chunk-size=500, checkpoint-dir=checkpoints, git-push=every 4 chunks) ...
      chunk 1/44 (rows 0-500) encoded & checkpointed. [500/21868 rows, 20s elapsed]
      chunk 2/44 (rows 500-1000) encoded & checkpointed. [1000/21868 rows, 41s elapsed]
      chunk 3/44 (rows 1000-1500) encoded & checkpointed. [1500/21868 rows, 63s elapsed]
      chunk 4/44 (rows 1500-2000) encoded & checkpointed. [2000/21868 rows, 84s elapsed]
  [git] pushed -> checkpoint: embeddings through chunk 3 (rows 0-2000/21868)
      chunk 5/44 (rows 2000-2500) encoded & checkpointed. [2500/21868 rows, 110s elapsed]
      chunk 6/44 (rows 2500-3000) encoded & checkpointed. [3000/21868 rows, 131s elapsed]
      chunk 7/44 (rows 3000-3500) encoded & checkpointed. [3500/21868 rows, 151s elapsed]
      chunk 8/44 (rows 3500-4000) encoded & checkpointed. [4000/21868 rows, 173s elapsed]
  [git] pushed -> checkpoint: embeddings through chunk 7 (rows 0-4000/21868)
      chunk 9/44 (rows 4000-4500) encoded & checkpointed. [4500/21868 rows, 199s elapsed]
      chunk 10/44 (rows 4500-5000) encoded & checkpointed. [5000/21868 rows, 221s elapsed]
      chunk 11/44 (rows 5000-5500) encoded & checkpointed. [5500/21868 rows, 243s elapsed]
      chunk 12/44 (rows 5500-6000) encoded & checkpointed. [6000/21868 rows, 265s elapsed]
  [git] pushed -> checkpoint: embeddings through chunk 11 (rows 0-6000/21868)
      chunk 13/44 (rows 6000-6500) encoded & checkpointed. [6500/21868 rows, 290s elapsed]
      chunk 14/44 (rows 6500-7000) encoded & checkpointed. [7000/21868 rows, 312s elapsed]
      chunk 15/44 (rows 7000-7500) encoded & checkpointed. [7500/21868 rows, 334s elapsed]
      chunk 16/44 (rows 7500-8000) encoded & checkpointed. [8000/21868 rows, 355s elapsed]
  [git] pushed -> checkpoint: embeddings through chunk 15 (rows 0-8000/21868)
      chunk 17/44 (rows 8000-8500) encoded & checkpointed. [8500/21868 rows, 381s elapsed]
      chunk 18/44 (rows 8500-9000) encoded & checkpointed. [9000/21868 rows, 403s elapsed]
      chunk 19/44 (rows 9000-9500) encoded & checkpointed. [9500/21868 rows, 425s elapsed]
      chunk 20/44 (rows 9500-10000) encoded & checkpointed. [10000/21868 rows, 447s elapsed]
  [git] pushed -> checkpoint: embeddings through chunk 19 (rows 0-10000/21868)
      chunk 21/44 (rows 10000-10500) encoded & checkpointed. [10500/21868 rows, 472s elapsed]
      chunk 22/44 (rows 10500-11000) encoded & checkpointed. [11000/21868 rows, 494s elapsed]
      chunk 23/44 (rows 11000-11500) encoded & checkpointed. [11500/21868 rows, 516s elapsed]
      chunk 24/44 (rows 11500-12000) encoded & checkpointed. [12000/21868 rows, 538s elapsed]
  [git] pushed -> checkpoint: embeddings through chunk 23 (rows 0-12000/21868)
      chunk 25/44 (rows 12000-12500) encoded & checkpointed. [12500/21868 rows, 562s elapsed]
      chunk 26/44 (rows 12500-13000) encoded & checkpointed. [13000/21868 rows, 584s elapsed]
      chunk 27/44 (rows 13000-13500) encoded & checkpointed. [13500/21868 rows, 607s elapsed]
      chunk 28/44 (rows 13500-14000) encoded & checkpointed. [14000/21868 rows, 629s elapsed]
  [git] pushed -> checkpoint: embeddings through chunk 27 (rows 0-14000/21868)
      chunk 29/44 (rows 14000-14500) encoded & checkpointed. [14500/21868 rows, 654s elapsed]
      chunk 30/44 (rows 14500-15000) encoded & checkpointed. [15000/21868 rows, 677s elapsed]
      chunk 31/44 (rows 15000-15500) encoded & checkpointed. [15500/21868 rows, 698s elapsed]
      chunk 32/44 (rows 15500-16000) encoded & checkpointed. [16000/21868 rows, 720s elapsed]
  [git] pushed -> checkpoint: embeddings through chunk 31 (rows 0-16000/21868)
      chunk 33/44 (rows 16000-16500) encoded & checkpointed. [16500/21868 rows, 744s elapsed]
      chunk 34/44 (rows 16500-17000) encoded & checkpointed. [17000/21868 rows, 767s elapsed]
      chunk 35/44 (rows 17000-17500) encoded & checkpointed. [17500/21868 rows, 788s elapsed]
      chunk 36/44 (rows 17500-18000) encoded & checkpointed. [18000/21868 rows, 810s elapsed]
  [git] pushed -> checkpoint: embeddings through chunk 35 (rows 0-18000/21868)
      chunk 37/44 (rows 18000-18500) encoded & checkpointed. [18500/21868 rows, 835s elapsed]
      chunk 38/44 (rows 18500-19000) encoded & checkpointed. [19000/21868 rows, 856s elapsed]
      chunk 39/44 (rows 19000-19500) encoded & checkpointed. [19500/21868 rows, 878s elapsed]
      chunk 40/44 (rows 19500-20000) encoded & checkpointed. [20000/21868 rows, 900s elapsed]
  [git] pushed -> checkpoint: embeddings through chunk 39 (rows 0-20000/21868)
      chunk 41/44 (rows 20000-20500) encoded & checkpointed. [20500/21868 rows, 924s elapsed]
      chunk 42/44 (rows 20500-21000) encoded & checkpointed. [21000/21868 rows, 946s elapsed]
      chunk 43/44 (rows 21000-21500) encoded & checkpointed. [21500/21868 rows, 967s elapsed]
      chunk 44/44 (rows 21500-21868) encoded & checkpointed. [21868/21868 rows, 984s elapsed]
  [git] pushed -> checkpoint: embeddings through chunk 43 (rows 0-21868/21868)
[5/5] Scoring + calibrating tags per axis ...
Done. Saved -> TOP_100_ARABIC_POETS_OF_ALL_TIME_STAGE_02A_mood_labeled.pkl
  [git] pushed -> Final labeled output: TOP_100_ARABIC_POETS_OF_ALL_TIME_STAGE_02A_mood_labeled.pkl (21868 rows)

20740/21868 rows have at least one shaky (low-margin) axis pick.
  mood: 10728 flagged
  genre: 9539 flagged
  energy: 15485 flagged
  aesthetic: 9995 flagged
              POET_NAME  ...                      flagged_axes
19916         احمد محرم  ...                     [mood, genre]
12766  العباس بن الاحنف  ...                    [mood, energy]
1317            البحتري  ...               [energy, aesthetic]
18479    الشريف المرتضا  ...                   [genre, energy]
19548         احمد محرم  ...  [mood, genre, energy, aesthetic]

[5 rows x 7 columns]

In [ ]:
#

In [ ]:
pwd

'/content/arabic-poetry-mood-labeling'

In [ ]:
!git push origin main

Everything up-to-date

In [12]:
df = pd.read_pickle('./TOP_100_ARABIC_POETS_OF_ALL_TIME_STAGE_02A_mood_labeled.pkl')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21868 entries, 0 to 21867
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   POET_NAME                 21868 non-null  object
 1   poem_no                   21868 non-null  object
 2   batch_no                  21868 non-null  int64
 3   POET_RANK                 21868 non-null  int64
 4   meter                     21868 non-null  object
 5   DATA                      21868 non-null  object
 6   BATCH_SIZE                21868 non-null  int64
 7   mood_tags                 21868 non-null  object
 8   mood_scores               21868 non-null  object
 9   mood_scores_z             21868 non-null  object
 10  mood_confidence           21868 non-null  float64
 11  mood_top2_gap             21868 non-null  float64
 12  mood_low_confidence       21868 non-null  bool
 13  genre_tags                21868 non-null  object
 14  genre_scores              21868 non-null  object
 15  genre_scores_z            21868 non-null  object
 16  genre_confidence          21868 non-null  float64
 17  genre_top2_gap            21868 non-null  float64
 18  genre_low_confidence      21868 non-null  bool
 19  energy_tags               21868 non-null  object
 20  energy_scores             21868 non-null  object
 21  energy_scores_z           21868 non-null  object
 22  energy_confidence         21868 non-null  float64
 23  energy_top2_gap           21868 non-null  float64
 24  energy_low_confidence     21868 non-null  bool
 25  aesthetic_tags            21868 non-null  object
 26  aesthetic_scores          21868 non-null  object
 27  aesthetic_scores_z        21868 non-null  object
 28  aesthetic_confidence      21868 non-null  float64
 29  aesthetic_top2_gap        21868 non-null  float64
 30  aesthetic_low_confidence  21868 non-null  bool
 31  flagged_axes              21868 non-null  object
 32  suno_tags                 21868 non-null  object
dtypes: bool(4), float64(8), int64(3), object(18)
memory usage: 4.9+ MB

In [14]:
df.to_pickle('./TOP_100_ARABIC_POETS_OF_ALL_TIME_STAGE_02_mood_labeled.pkl', protocol=4)

In [15]:
df.to_pickle('./TOP_100_ARABIC_POETS_OF_ALL_TIME_STAGE_02A_mood_labeled.pkl', protocol=4)

In [16]:
pwd

'/content/arabic-poetry-mood-labeling'

In [17]:
!git add -A

In [18]:
!git commit -m "Output saved in protocol 4"

[main 101fe9e] Output saved in protocol 4
 2 files changed, 0 insertions(+), 0 deletions(-)

In [19]:
!git push origin main

Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 7.57 MiB | 1.67 MiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: warning: See https://gh.io/lfs for more information.
remote: warning: File TOP_100_ARABIC_POETS_OF_ALL_TIME_STAGE_02A_mood_labeled.pkl is 56.12 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/akbargherbal/arabic-poetry-mood-labeling.git
   97b83c1..101fe9e  main -> main

In [20]:
#